"""Convert percent-format .py sources (# %% / # %% [markdown]) into .ipynb.

Every generated notebook also gets two cells right after its title: an "Open in Colab" badge
and a Colab setup cell. The setup cell does nothing outside Google Colab. In Colab it clones
the public repo, changes into labs/, installs only the packages this lab needs that Colab
doesn't ship, and loads API keys from Colab Secrets. Edit COLAB_PACKAGES or the template
here, never the notebooks.
"""
import sys
from pathlib import Path

import nbformat

REPO = "sp7412/onboarding"
SECRET_KEYS = ("OPENAI_API_KEY", "LANGSMITH_API_KEY", "LIVEKIT_URL", "LIVEKIT_API_KEY",
               "LIVEKIT_API_SECRET")
# Packages each lab needs beyond Colab's preinstalled stack (numpy, pandas, matplotlib, ...).
# Keep these minimal: installing all of requirements.txt is slow and can replace Colab's own
# versions mid-session.
COLAB_PACKAGES: dict[str, list[str]] = {
    "01": ["websockets>=13"],
    "02": ["websockets>=13"],
    "04": ["livekit-agents[openai,silero,turn-detector]>=1.8"],
    "05": ["langchain>=1.0", "langchain-openai", "langgraph"],
    "06": ["langgraph", "langgraph-checkpoint-sqlite"],
    "07": ["websockets>=13", "langchain>=1.0", "langchain-openai", "langgraph", "langsmith>=0.4"],
    "08": ["websockets>=13", "langchain>=1.0", "langchain-openai", "langgraph", "langsmith>=0.4"],
    "15": ["openai"],
}
COLAB_NOTES = {
    "04": "The offline sections run in Colab; the live LiveKit agent needs a terminal and a "
          "microphone, so run that part locally or in Codespaces.",
}


def colab_badge_cell(stem: str) -> nbformat.NotebookNode:
    url = f"https://colab.research.google.com/github/{REPO}/blob/main/labs/{stem}.ipynb"
    text = (f"[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)]({url})\n\n"
            "**Running in Google Colab?** Run the next cell first: it fetches the repo and this "
            "lab's packages. For live mode, add your keys (for example `OPENAI_API_KEY`) under "
            "Colab's **Secrets** panel (key icon) and allow notebook access. Outside Colab the cell "
            "does nothing.")
    note = COLAB_NOTES.get(stem[:2])
    if note:
        text += "\n\n" + note
    return nbformat.v4.new_markdown_cell(text)


def colab_setup_cell(stem: str) -> nbformat.NotebookNode:
    packages = COLAB_PACKAGES.get(stem[:2], [])
    code = f'''# Colab setup: does nothing outside Google Colab. Generated by labs/build_nb.py.
import os
import sys

if "google.colab" in sys.modules and not os.path.isdir("stlab"):
    import subprocess

    repo = "/content/onboarding"
    if not os.path.isdir(repo):
        subprocess.run(["git", "clone", "--depth", "1", "-q",
                        "https://github.com/{REPO}.git", repo], check=True)
    os.chdir(os.path.join(repo, "labs"))
    sys.path.insert(0, os.getcwd())
    packages = {packages!r}
    if packages:
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", *packages], check=True)
    from google.colab import userdata

    for key in {SECRET_KEYS!r}:
        try:
            value = userdata.get(key)
        except Exception:  # secret not set, or notebook access not granted
            value = None
        if value:
            os.environ.setdefault(key, value)
    print("Colab ready in", os.getcwd(), "| extra packages:", ", ".join(packages) or "none")'''
    return nbformat.v4.new_code_cell(code)


def convert(src: Path, dst: Path):
    cells, kind, buf = [], None, []
    def flush():
        if kind is None: return
        text = "\n".join(buf).strip("\n")
        if kind == "md":
            text = "\n".join(l[2:] if l.startswith("# ") else ("" if l == "#" else l) for l in text.splitlines())
            cells.append(nbformat.v4.new_markdown_cell(text))
        elif text:
            cells.append(nbformat.v4.new_code_cell(text))
    for line in src.read_text().splitlines():
        if line.startswith("# %% [markdown]"):
            flush(); kind, buf = "md", []
        elif line.startswith("# %%"):
            flush(); kind, buf = "code", []
        else:
            buf.append(line)
    flush()
    if not cells or cells[0].cell_type != "markdown":
        sys.exit(f"{src}: the first cell must be the markdown title")
    cells[1:1] = [colab_badge_cell(src.stem), colab_setup_cell(src.stem)]
    nb = nbformat.v4.new_notebook(cells=cells, metadata={
        "kernelspec": {"name": "python3", "display_name": "Python 3", "language": "python"},
        "language_info": {"name": "python"}})
    nbformat.write(nb, dst)

if __name__ == "__main__":
    for s in sorted(Path("src").glob("*.py")):
        convert(s, Path(s.stem + ".ipynb")); print("built", s.stem)
